### ISSUE TITLE
Hey, sorry but I have a question I wanna ask you.

### ISSUE THREAD

**Issue by Zai-Kun** [yoshikuniii/pynime#5]
How did you figure out how to extract .m3u8 URL?

**Comment by yoshikuniii** [comment]
Oh yeah, sure. All I know the URL is locked behind an encryption, so we need to decrypt it. Luckly, someone already write the code for it. You can go ahead check this repo : [https://github.com/justfoolingaround/animdl](https://github.com/justfoolingaround/animdll), head to `.../animdl/core/codebase/extractors`. 

Maybe you can ask people there. Sorry if this is not the answer you wanted.

**Comment by Zai-Kun** [comment]
Oh no, it helped! Thanks.

I'll look into it.
